-- MySQL Script generated by MySQL Workbench
-- Mon Jun 19 14:54:15 2017
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema _infotech_base
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `_infotech_base` ;

-- -----------------------------------------------------
-- Schema _infotech_base
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `_infotech_base` DEFAULT CHARACTER SET utf8 ;
USE `_infotech_base` ;

-- -----------------------------------------------------
-- Table `_infotech_base`.`Administrador`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Administrador` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Administrador` (
  `id` INT NOT NULL AUTO_INCREMENT,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Cliente` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cpf` INT(11) NOT NULL,
  `rg` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cpf_UNIQUE` (`cpf` ASC),
  UNIQUE INDEX `rg_UNIQUE` (`rg` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Endereco`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Endereco` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Endereco` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `logradouro` VARCHAR(100) NULL,
  `cep` VARCHAR(9) NULL,
  `cidade` VARCHAR(100) NULL,
  `uf` VARCHAR(2) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Usuario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Usuario` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Usuario` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `email` VARCHAR(45) NOT NULL,
  `senha` VARCHAR(45) NOT NULL,
  `nome` VARCHAR(45) NOT NULL,
  `usuario_administrador_id` INT NULL,
  `usuario_cliente_id` INT NULL,
  `usuario_endereco_id` INT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `email_UNIQUE` (`email` ASC),
  INDEX `usuario_administrador_id` (`usuario_administrador_id` ASC),
  INDEX `usuario_cliente_id` (`usuario_cliente_id` ASC),
  INDEX `usuario_endereco_id` (`usuario_endereco_id` ASC),
  CONSTRAINT `usuario_administrador_id`
    FOREIGN KEY (`usuario_administrador_id`)
    REFERENCES `_infotech_base`.`Administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_cliente_id`
    FOREIGN KEY (`usuario_cliente_id`)
    REFERENCES `_infotech_base`.`Cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `usuario_endereco_id`
    FOREIGN KEY (`usuario_endereco_id`)
    REFERENCES `_infotech_base`.`Endereco` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Suporte`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Suporte` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Suporte` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `descricao` LONGTEXT NOT NULL,
  `assunto` VARCHAR(45) NOT NULL,
  `suporte_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `suporte_cliente_id` (`suporte_cliente_id` ASC),
  CONSTRAINT `suporte_cliente_id`
    FOREIGN KEY (`suporte_cliente_id`)
    REFERENCES `_infotech_base`.`Cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Cadastro`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Cadastro` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Cadastro` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `cadastro_administrador_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cadastro_administrador_id` (`cadastro_administrador_id` ASC),
  CONSTRAINT `cadastro_administrador_id`
    FOREIGN KEY (`cadastro_administrador_id`)
    REFERENCES `_infotech_base`.`Administrador` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Categoria`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Categoria` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Categoria` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `categoria_cadastro_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `categoria_cadastro_id` (`categoria_cadastro_id` ASC),
  CONSTRAINT `categoria_cadastro_id`
    FOREIGN KEY (`categoria_cadastro_id`)
    REFERENCES `_infotech_base`.`Cadastro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Produto`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Produto` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Produto` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `nome` VARCHAR(45) NOT NULL,
  `descricao` LONGTEXT NOT NULL,
  `estoque_quantidade` INT NOT NULL,
  `preco` DOUBLE NOT NULL,
  `produto_cadastro_id` INT NOT NULL,
  `produto_categoria_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `nome_UNIQUE` (`nome` ASC),
  INDEX `produto_cadastro_id` (`produto_cadastro_id` ASC),
  INDEX `produto_categoria_id` (`produto_categoria_id` ASC),
  CONSTRAINT `produto_cadastro_id`
    FOREIGN KEY (`produto_cadastro_id`)
    REFERENCES `_infotech_base`.`Cadastro` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `produto_categoria_id`
    FOREIGN KEY (`produto_categoria_id`)
    REFERENCES `_infotech_base`.`Categoria` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Imagem`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Imagem` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Imagem` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `url` VARCHAR(45) NOT NULL,
  `imagem_produto_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `url_UNIQUE` (`url` ASC),
  INDEX `imagem_produto_id` (`imagem_produto_id` ASC),
  CONSTRAINT `imagem_produto_id`
    FOREIGN KEY (`imagem_produto_id`)
    REFERENCES `_infotech_base`.`Produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Cartao_de_credito`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Cartao_de_credito` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Cartao_de_credito` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_seguranca` INT NOT NULL,
  `numero` INT NOT NULL,
  `validade` DATE NOT NULL,
  PRIMARY KEY (`id`),
  UNIQUE INDEX `cod_seguranca_UNIQUE` (`cod_seguranca` ASC),
  UNIQUE INDEX `numero_UNIQUE` (`numero` ASC))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Cesta`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Cesta` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Cesta` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `cod_barras` VARCHAR(100) NOT NULL,
  `emissao` DATE NOT NULL,
  `vencimento` DATE NOT NULL,
  `status` VARCHAR(45) NULL,
  `valor` DOUBLE NULL,
  `cesta_cliente_id` INT NOT NULL,
  `cesta_cartao_de_credito_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `cesta_cliente_id` (`cesta_cliente_id` ASC),
  INDEX `cesta_cartao_de_credito_id` (`cesta_cartao_de_credito_id` ASC),
  UNIQUE INDEX `cod_barras_UNIQUE` (`cod_barras` ASC),
  CONSTRAINT `cesta_cliente_id`
    FOREIGN KEY (`cesta_cliente_id`)
    REFERENCES `_infotech_base`.`Cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `cesta_cartao_de_credito_id`
    FOREIGN KEY (`cesta_cartao_de_credito_id`)
    REFERENCES `_infotech_base`.`Cartao_de_credito` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Compra` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Compra` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `data` DATETIME NOT NULL,
  `valor` DOUBLE NOT NULL,
  `quantidade` INT NOT NULL,
  `compra_produto_id` INT NOT NULL,
  `compra_cesta_id` INT NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `compra_produto_id` (`compra_produto_id` ASC),
  INDEX `compra_cesta_id` (`compra_cesta_id` ASC),
  CONSTRAINT `compra_produto_id`
    FOREIGN KEY (`compra_produto_id`)
    REFERENCES `_infotech_base`.`Produto` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `compra_cesta_id`
    FOREIGN KEY (`compra_cesta_id`)
    REFERENCES `_infotech_base`.`Cesta` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `_infotech_base`.`Cartao_de_credito_Cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `_infotech_base`.`Cartao_de_credito_Cliente` ;

CREATE TABLE IF NOT EXISTS `_infotech_base`.`Cartao_de_credito_Cliente` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `ccc_cartao_de_credito_id` INT NOT NULL,
  `ccc_cliente_id` INT NOT NULL,
  PRIMARY KEY (`id`, `ccc_cartao_de_credito_id`, `ccc_cliente_id`),
  INDEX `ccc_cliente_id` (`ccc_cliente_id` ASC),
  INDEX `ccc_cartao_de_credito_id` (`ccc_cartao_de_credito_id` ASC),
  CONSTRAINT `ccc_cartao_de_credito_id`
    FOREIGN KEY (`ccc_cartao_de_credito_id`)
    REFERENCES `_infotech_base`.`Cartao_de_credito` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE,
  CONSTRAINT `ccc_cliente_id`
    FOREIGN KEY (`ccc_cliente_id`)
    REFERENCES `_infotech_base`.`Cliente` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;

INSERT INTO administrador VALUES (1);
insert into usuario values(null,'admin@gmail.com','123','administrador',1,null,null);